'use strict';
// ╔══════════════════════════════════════════════════════════════╗
// SMURF-XMD — David Cyril API plugins
// Endpoints: https://apis.davidcyril.name.ng
// ╚══════════════════════════════════════════════════════════════╝

const axios = require('axios');
const { addCmd } = require('../../smurf/handlers/loader');
const { channelCtx } = require('../../smurf/utils/gmdFunctions2');

const DC_BASE = 'https://apis.davidcyril.name.ng';
const TIMEOUT = 60_000;

async function dcJson(path) {
    const { data } = await axios.get(`${DC_BASE}${path}`, { timeout: TIMEOUT });
    return data;
}

async function dcBuffer(path) {
    const { data } = await axios.get(`${DC_BASE}${path}`, {
        timeout: TIMEOUT,
        responseType: 'arraybuffer',
    });
    return Buffer.from(data);
}

// ── DEEPSEEK V3 ──────────────────────────────────────────────
addCmd({
    name: 'deepseek',
    aliases: ['ds', 'ds3'],
    desc: 'Chat with DeepSeek-V3 AI',
    usage: 'deepseek <prompt>',
    category: 'ai',
    handler: async (ctx) => {
        const q = (ctx.args || []).join(' ').trim();
        if (!q) return ctx.reply('Usage: `.deepseek <your prompt>`');
        await ctx.react('').catch(() => {});
        try {
            const r = await dcJson(`/ai/deepseek-v3?text=${encodeURIComponent(q)}`);
            const ans = r?.response || r?.message || r?.result || '_(no answer)_';
            await ctx.reply(`*DeepSeek V3*\n\n${ans}`);
        } catch (e) {
            await ctx.reply(`DeepSeek failed: ${e.message}`);
        }
    },
});

// ── GPT-4 ────────────────────────────────────────────────────
addCmd({
    name: 'gpt4',
    aliases: ['gpt'],
    desc: 'Chat with GPT-4',
    usage: 'gpt4 <prompt>',
    category: 'ai',
    handler: async (ctx) => {
        const q = (ctx.args || []).join(' ').trim();
        if (!q) return ctx.reply('Usage: `.gpt4 <your prompt>`');
        await ctx.react('').catch(() => {});
        try {
            const r = await dcJson(`/ai/gpt4?text=${encodeURIComponent(q)}`);
            const ans = r?.message || r?.response || r?.result || '_(no answer)_';
            await ctx.reply(`*GPT-4*\n\n${ans}`);
        } catch (e) {
            await ctx.reply(`GPT-4 failed: ${e.message}`);
        }
    },
});

// ── DALL-E IMAGE GEN ─────────────────────────────────────────
addCmd({
    name: 'dalle',
    aliases: ['imagine', 'aiimg', 'aiimage'],
    desc: 'Generate an AI image from text',
    usage: 'dalle <prompt>',
    category: 'ai',
    handler: async (ctx) => {
        const q = (ctx.args || []).join(' ').trim();
        if (!q) return ctx.reply('Usage: `.dalle <prompt>`\nExample: `.dalle a black smurf in smurf`');
        await ctx.react('').catch(() => {});
        try {
            const buf = await dcBuffer(`/ai/dalle?text=${encodeURIComponent(q)}`);
            await ctx.send({
                image: buf,
                caption: `*${q}*\n_Generated by DALL-E_`,
            });
        } catch (e) {
            await ctx.reply(`Image generation failed: ${e.message}`);
        }
    },
});
